version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    working_dir: /frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
